[2024-07-26T05:58:18.232+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-26T05:58:18.240+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: minio_dag.minio_sensor scheduled__2024-07-25T00:00:00+00:00 [queued]>
[2024-07-26T05:58:18.244+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: minio_dag.minio_sensor scheduled__2024-07-25T00:00:00+00:00 [queued]>
[2024-07-26T05:58:18.244+0000] {taskinstance.py:2306} INFO - Starting attempt 5 of 6
[2024-07-26T05:58:18.249+0000] {taskinstance.py:2330} INFO - Executing <Task(S3KeySensor): minio_sensor> on 2024-07-25 00:00:00+00:00
[2024-07-26T05:58:18.252+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:62: DeprecationWarning: This process (pid=475) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-07-26T05:58:18.253+0000] {standard_task_runner.py:64} INFO - Started process 476 to run task
[2024-07-26T05:58:18.253+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'minio_dag', 'minio_sensor', 'scheduled__2024-07-25T00:00:00+00:00', '--job-id', '13', '--raw', '--subdir', 'DAGS_FOLDER/7_minio_dag.py', '--cfg-path', '/tmp/tmpepuv5hw7']
[2024-07-26T05:58:18.254+0000] {standard_task_runner.py:91} INFO - Job 13: Subtask minio_sensor
[2024-07-26T05:58:18.298+0000] {task_command.py:426} INFO - Running <TaskInstance: minio_dag.minio_sensor scheduled__2024-07-25T00:00:00+00:00 [running]> on host ecd5bbc03de3
[2024-07-26T05:58:18.343+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Bossixd' AIRFLOW_CTX_DAG_ID='minio_dag' AIRFLOW_CTX_TASK_ID='minio_sensor' AIRFLOW_CTX_EXECUTION_DATE='2024-07-25T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='5' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-07-25T00:00:00+00:00'
[2024-07-26T05:58:18.344+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-26T05:58:18.360+0000] {baseoperator.py:400} WARNING - S3KeySensor.execute cannot be called outside TaskInstance!
[2024-07-26T05:58:18.361+0000] {s3.py:117} INFO - Poking for key : s3://***/data.csv
[2024-07-26T05:58:18.371+0000] {base.py:84} INFO - Using connection ID 'minio_localhost' for task execution.
[2024-07-26T05:58:18.372+0000] {connection_wrapper.py:384} INFO - AWS Connection (conn_id='minio_localhost', conn_type='aws') credentials retrieved from login and ***.
[2024-07-26T05:58:18.723+0000] {base.py:294} INFO - Success criteria met. Exiting.
[2024-07-26T05:58:18.724+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-07-26T05:58:18.732+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=minio_dag, task_id=minio_sensor, run_id=scheduled__2024-07-25T00:00:00+00:00, execution_date=20240725T000000, start_date=20240726T055818, end_date=20240726T055818
[2024-07-26T05:58:18.771+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 0
[2024-07-26T05:58:18.779+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-07-26T05:58:18.780+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
