[2024-07-26T06:00:48.423+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-26T06:00:48.429+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: minio_dag.minio_sensor manual__2024-07-26T06:00:47.678221+00:00 [queued]>
[2024-07-26T06:00:48.432+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: minio_dag.minio_sensor manual__2024-07-26T06:00:47.678221+00:00 [queued]>
[2024-07-26T06:00:48.432+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 6
[2024-07-26T06:00:48.436+0000] {taskinstance.py:2330} INFO - Executing <Task(S3KeySensor): minio_sensor> on 2024-07-26 06:00:47.678221+00:00
[2024-07-26T06:00:48.440+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:62: DeprecationWarning: This process (pid=516) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-07-26T06:00:48.441+0000] {standard_task_runner.py:64} INFO - Started process 517 to run task
[2024-07-26T06:00:48.441+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'minio_dag', 'minio_sensor', 'manual__2024-07-26T06:00:47.678221+00:00', '--job-id', '16', '--raw', '--subdir', 'DAGS_FOLDER/7_minio_dag.py', '--cfg-path', '/tmp/tmpfdez7_lm']
[2024-07-26T06:00:48.442+0000] {standard_task_runner.py:91} INFO - Job 16: Subtask minio_sensor
[2024-07-26T06:00:48.460+0000] {task_command.py:426} INFO - Running <TaskInstance: minio_dag.minio_sensor manual__2024-07-26T06:00:47.678221+00:00 [running]> on host ecd5bbc03de3
[2024-07-26T06:00:48.490+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Bossixd' AIRFLOW_CTX_DAG_ID='minio_dag' AIRFLOW_CTX_TASK_ID='minio_sensor' AIRFLOW_CTX_EXECUTION_DATE='2024-07-26T06:00:47.678221+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-07-26T06:00:47.678221+00:00'
[2024-07-26T06:00:48.491+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-26T06:00:48.497+0000] {baseoperator.py:400} WARNING - S3KeySensor.execute cannot be called outside TaskInstance!
[2024-07-26T06:00:48.498+0000] {s3.py:117} INFO - Poking for key : s3://***/data.csv
[2024-07-26T06:00:48.502+0000] {base.py:84} INFO - Using connection ID 'minio_localhost' for task execution.
[2024-07-26T06:00:48.502+0000] {connection_wrapper.py:384} INFO - AWS Connection (conn_id='minio_localhost', conn_type='aws') credentials retrieved from login and ***.
[2024-07-26T06:00:53.687+0000] {s3.py:117} INFO - Poking for key : s3://***/data.csv
[2024-07-26T06:00:58.711+0000] {s3.py:117} INFO - Poking for key : s3://***/data.csv
[2024-07-26T06:01:03.762+0000] {s3.py:117} INFO - Poking for key : s3://***/data.csv
[2024-07-26T06:01:08.791+0000] {s3.py:117} INFO - Poking for key : s3://***/data.csv
[2024-07-26T06:01:08.816+0000] {base.py:294} INFO - Success criteria met. Exiting.
[2024-07-26T06:01:08.820+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-07-26T06:01:08.848+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=minio_dag, task_id=minio_sensor, run_id=manual__2024-07-26T06:00:47.678221+00:00, execution_date=20240726T060047, start_date=20240726T060048, end_date=20240726T060108
[2024-07-26T06:01:08.886+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 0
[2024-07-26T06:01:08.899+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-07-26T06:01:08.900+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
